export const queryKeys = {
  admins: ['admins'] as const,
  admin: (id: string) => ['admins', id] as const,
  centers: ['centers'] as const,
  center: (id: string) => ['centers', id] as const,
  subjects: ['subjects'] as const,
  subject: (id: string) => ['subjects', id] as const,
  subjectsBySession: (sessionId: string) => ['subjects', 'session', sessionId] as const,
  subjectsWithQuestions: (sessionId: string) => ['subjects', 'with-questions', sessionId] as const,
  questionsBySubjectAndSession: (subjectId: string, sessionId: string) =>
    ['questions', 'by-subject-session', subjectId, sessionId] as const,
  questionCount: (subjectId: string | undefined, sessionId: string | undefined) =>
    ['questions', 'count', subjectId ?? 'all', sessionId ?? 'all'] as const,
  examSessions: ['exam-sessions'] as const,
  examSession: (id: string) => ['exam-sessions', id] as const,
  completedExamSessions: ['exam-sessions', 'completed'] as const,
  sessionAnalysis: (sessionId: string) => ['sessions', sessionId, 'analysis'] as const,
  sessionStatistics: (sessionId: string) => ['sessions', sessionId, 'statistics'] as const,
  sessionScores: (sessionId: string) => ['sessions', sessionId, 'scores'] as const,
  candidates: ['candidates'] as const,
  candidate: (id: string) => ['candidates', id] as const,
  aiModels: ['ai-models'] as const,
  apiConfigurations: ['api-configurations'] as const,
  apiConfigurationsByCenter: (centerId: string) => ['api-configurations', 'by-center', centerId] as const,
  scoreConfigurations: ['score-configurations'] as const,
  scoreConfigurationsByCenter: (centerId: string) => ['score-configurations', 'by-center', centerId] as const,
  activeScoreConfiguration: (centerId: string) => ['score-configurations', 'active', centerId] as const,
  metricsSummary: ['metrics', 'summary'] as const,
  metricsActivity: ['metrics', 'activity'] as const,
  monitoringSessions: ['monitoring', 'sessions'] as const,
  monitoringSession: (sessionId: string) => ['monitoring', 'sessions', sessionId] as const,
  monitoringStatistics: (sessionId: string) => ['monitoring', 'sessions', sessionId, 'statistics'] as const,
  monitoringProgress: (sessionId: string) => ['monitoring', 'sessions', sessionId, 'progress'] as const,
} as const
